---
title: "Running Analysis"
author: "Grace Abels"
date: "2022-11-02"
output: pdf_document
---

```{r load packages, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(knitr)
library(lubridate)
```

```{r read in data, message=FALSE, warning=FALSE, echo=FALSE}
runs <- read.csv("allruns2.csv")
runs["14", "kcal"] <- 331
```


```{r message=FALSE, warning=FALSE, echo=FALSE}
runs %>% 
  group_by(instructor)%>%
  summarise( Count = n(),
             `Average Distance` = mean(miles), 
            `Average Speed` = mean(avg_speed), 
            `Average BPM` = mean(avg_bpm), 
            `Average Strive Score` = mean(strive_score), 
            `Average kCal` = mean(kcal), 
            `Average Run Time` = mean(run_time))%>%
    arrange(desc(Count)) %>%
  kable( caption = "Stats by Instructor", digits = 2)

```
\pagebreak
```{r message=FALSE, warning=FALSE, echo=FALSE}
runs %>% 
  group_by(run_type)%>%
  summarise(Count = n(),
            `Average Distance` = mean(miles), 
            `Average Speed` = mean(avg_speed), 
            `Average BPM` = mean(avg_bpm), 
            `Average Strive Score` = mean(strive_score), 
            `Average kCal` = mean(kcal), 
            `Average Run Time` = mean(run_time)) %>%
   arrange(desc(Count)) %>%
  kable(  caption = "Stats by Run Type",digits = 2)

```


```{r message=FALSE, warning=FALSE, echo=FALSE}

runs %>% 
  group_by(morn_aft) %>%
  summarise( Count = n(),
             `Average Distance` = mean(miles), 
            `Average Speed` = mean(avg_speed), 
            `Average BPM` = mean(avg_bpm), 
            `Average Strive Score` = mean(strive_score), 
            `Average kCal` = mean(kcal), 
            `Average Run Time` = mean(run_time)) %>%
  arrange(desc(Count)) %>%
  kable( caption = "Stats for Morning versus Afternoon Runs",digits = 2)

```